name: CI

on: [push]

jobs:
  testing:
    name: Lint Runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install packages
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Lint code
        run: yarn lint
